import countryData from "./country.json";
import cityData from "./cities.json";
import stateData from "./state.json";
import institutionData from "./college.json";

// Options for the select fields
export const willingnessOptions = [
  { value: "No", label: "No" },
  { value: "Yes", label: "Yes" },
  { value: "May be", label: "May be" },
];

export const workingHoursOptions = [
  { value: "Day Shift", label: "Day Shift" },
  { value: "Night Shift", label: "Night Shift" },
  { value: "Flexible", label: "Flexible" },
];

export const companySizeOptions = [
  { value: "Startup", label: "Startup (1-50 employees)" },
  { value: "Small", label: "Small (51-200 employees)" },
  { value: "Medium", label: "Medium (201-500 employees)" },
  { value: "Large", label: "Large (501+ employees)" },
];

export const workEnvironmentOptions = [
  { value: "Remote", label: "Remote" },
  { value: "On-site", label: "On-site" },
  { value: "Hybrid", label: "Hybrid" },
];

export const roleLevelOptions = [
  { value: "Entry-level", label: "Entry-level" },
  { value: "Mid-level", label: "Mid-level" },
  { value: "Senior-level", label: "Senior-level" },
  { value: "Executive", label: "Executive" },
];

export const benefitsOptions = [
  { value: "Health Insurance", label: "Health Insurance" },
  { value: "Retirement Plan", label: "Retirement Plan" },
  { value: "Paid Time Off", label: "Paid Time Off" },
  { value: "Remote Work Options", label: "Remote Work Options" },
  { value: "Professional Development", label: "Professional Development" },
  { value: "Other", label: "Other" },
];

export const companyCultureOptions = [
  { value: "Collaborative", label: "Collaborative" },
  { value: "Innovative", label: "Innovative" },
  { value: "Traditional", label: "Traditional" },
  { value: "Inclusive", label: "Inclusive" },
  { value: "Other", label: "Other" },
];

export const currencyOptions = [
  { value: "USD", label: "USD" },
  { value: "EUR", label: "EUR" },
  { value: "JPY", label: "JPY" },
  { value: "GBP", label: "GBP" },
  { value: "AUD", label: "AUD" },
  { value: "CAD", label: "CAD" },
  { value: "CHF", label: "CHF" },
  { value: "CNY", label: "CNY" },
  { value: "SEK", label: "SEK" },
  { value: "NZD", label: "NZD" },
  { value: "MXN", label: "MXN" },
  { value: "SGD", label: "SGD" },
  { value: "HKD", label: "HKD" },
  { value: "NOK", label: "NOK" },
  { value: "KRW", label: "KRW" },
  { value: "TRY", label: "TRY" },
  { value: "INR", label: "INR" },
  { value: "RUB", label: "RUB" },
  { value: "BRL", label: "BRL" },
  { value: "ZAR", label: "ZAR" },
];

export const jobCategories = {
  "IT & Software Development": [
    "Full Stack Developer",
    "Front-End Developer",
    "Back-End Developer",
    "UI/UX Designer",
    "Software Engineer",
    "DevOps Engineer",
    "Mobile App Developer",
    "Data Scientist",
    "Machine Learning Engineer",
    "AI Engineer",
    "Database Administrator",
    "Cybersecurity Analyst",
    "Cloud Architect",
    "QA Engineer",
    "Network Engineer",
  ],
  "Marketing & Sales": [
    "Digital Marketing Specialist",
    "SEO Specialist",
    "Content Writer",
    "Social Media Manager",
    "Marketing Manager",
    "Sales Executive",
    "Business Development Manager",
    "Account Manager",
  ],
  "Finance & Accounting": [
    "Financial Analyst",
    "Accountant",
    "Auditor",
    "Investment Analyst",
    "Tax Consultant",
    "Risk Manager",
    "Treasury Analyst",
  ],
  "Human Resources": [
    "HR Manager",
    "Recruitment Specialist",
    "HR Generalist",
    "Payroll Specialist",
    "Employee Relations Manager",
  ],
  "Operations & Management": [
    "Operations Manager",
    "Project Manager",
    "Supply Chain Manager",
    "Logistics Coordinator",
    "Business Analyst",
  ],
  "Creative & Design": [
    "Graphic Designer",
    "Video Editor",
    "Copywriter",
    "Animator",
    "Creative Director",
  ],
  "Customer Service & Support": [
    "Customer Service Representative",
    "Technical Support Specialist",
    "Call Center Agent",
    "Client Support Specialist",
    "Customer Success Manager",
  ],
  "Engineering & Technical": [
    "Mechanical Engineer",
    "Electrical Engineer",
    "Civil Engineer",
    "Chemical Engineer",
    "Environmental Engineer",
  ],
  "Healthcare & Pharmaceuticals": [
    "Registered Nurse",
    "Pharmacist",
    "Medical Laboratory Technician",
    "Physical Therapist",
    "Healthcare Administrator",
  ],
  "Education & Training": [
    "Teacher",
    "Academic Advisor",
    "Instructional Designer",
    "Training Specialist",
    "Education Consultant",
  ],
  Legal: [
    "Lawyer",
    "Paralegal",
    "Legal Assistant",
    "Compliance Officer",
    "Contract Manager",
  ],
  "Administration & Office Support": [
    "Administrative Assistant",
    "Office Manager",
    "Executive Assistant",
    "Data Entry Clerk",
    "Receptionist",
  ],
  Others: [
    "Event Coordinator",
    "Public Relations Specialist",
    "Research Analyst",
    "Quality Assurance Specialist",
    "Product Manager",
  ],
};

export const jobTitles = [
  "Full Stack Developer",
  "Front End Developer",
  "Backend Developer",
  "Mobile App Developer (iOS/Android)",
  "DevOps Engineer",
  "Cloud Computing Specialist",
  "Cybersecurity Analyst",
  "Database Administrator",
  "UI/UX Designer",
  "Game Developer",
  "Blockchain Developer",
  "AR/VR Developer",
  "Data Scientist",
  "Machine Learning Engineer",
  "Business Intelligence Analyst",
  "Big Data Engineer",
  "Statistician",
  "Quantitative Analyst",
  "Mechanical Engineer",
  "Electrical Engineer",
  "Civil Engineer",
  "Chemical Engineer",
  "Aerospace Engineer",
  "Biomedical Engineer",
  "Environmental Engineer",
  "Robotics Engineer",
  "Materials Scientist",
  "Financial Analyst",
  "Investment Banker",
  "Management Consultant",
  "Project Manager",
  "Business Development Manager",
  "Human Resources Manager",
  "Supply Chain Manager",
  "Operations Manager",
  "Risk Analyst",
  "Chartered Accountant",
  "Digital Marketing Specialist",
  "Content Strategist",
  "Social Media Manager",
  "Brand Manager",
  "Public Relations Specialist",
  "SEO Specialist",
  "Copywriter",
  "Marketing Analytics Manager",
  "Graphic Designer",
  "Industrial Designer",
  "Fashion Designer",
  "Interior Designer",
  "3D Modeler",
  "Motion Graphics Designer",
  "UX Researcher",
  "Physician",
  "Nurse Practitioner",
  "Pharmacist",
  "Biotechnologist",
  "Clinical Research Associate",
  "Nutritionist/Dietitian",
  "Bioinformatics Specialist",
  "Corporate Lawyer",
  "Patent Attorney",
  "Compliance Officer",
  "Legal Researcher",
  "Paralegal",
  "University Professor",
  "Research Scientist",
  "Data Analyst",
  "Curriculum Developer",
  "Instructional Designer",
  "Education Technology Specialist",
  "Film Director",
  "Video Editor",
  "Sound Engineer",
  "Animator",
  "Journalist",
  "Game Designer",
  "Podcaster",
  "Environmental Scientist",
  "Sustainability Consultant",
  "Renewable Energy Engineer",
  "Conservation Biologist",
  "Urban Planner",
  "Hotel Manager",
  "Event Planner",
  "Travel Consultant",
  "Chef",
  "Restaurant Manager",
  "Sales Manager",
  "Account Executive",
  "Customer Success Manager",
  "Technical Support Specialist",
  "Product Manager",
  "Quality Assurance Engineer",
  "Systems Administrator",
  "Network Engineer",
  "Information Security Analyst",
  "Business Analyst",
  "Data Engineer",
  "UX/UI Developer",
  "Technical Writer",
  "Scrum Master",
];

export const skillOptions = [
  { value: "javascript", label: "JavaScript" },
  { value: "python", label: "Python" },
  { value: "java", label: "Java" },
  { value: "csharp", label: "C#" },
  { value: "cpp", label: "C++" },
  { value: "php", label: "PHP" },
  { value: "ruby", label: "Ruby" },
  { value: "swift", label: "Swift" },
  { value: "go", label: "Go" },
  { value: "rust", label: "Rust" },
  { value: "typescript", label: "TypeScript" },
  { value: "kotlin", label: "Kotlin" },
  { value: "scala", label: "Scala" },
  { value: "r", label: "R" },
  { value: "matlab", label: "MATLAB" },
  { value: "sql", label: "SQL" },
  { value: "nosql", label: "NoSQL" },
  { value: "mongodb", label: "MongoDB" },
  { value: "postgresql", label: "PostgreSQL" },
  { value: "mysql", label: "MySQL" },
  { value: "oracle", label: "Oracle" },
  { value: "react", label: "React" },
  { value: "angular", label: "Angular" },
  { value: "vue", label: "Vue.js" },
  { value: "nodejs", label: "Node.js" },
  { value: "express", label: "Express.js" },
  { value: "django", label: "Django" },
  { value: "flask", label: "Flask" },
  { value: "spring", label: "Spring" },
  { value: "aspnet", label: "ASP.NET" },
  { value: "laravel", label: "Laravel" },
  { value: "ruby_on_rails", label: "Ruby on Rails" },
  { value: "html", label: "HTML" },
  { value: "css", label: "CSS" },
  { value: "sass", label: "Sass" },
  { value: "less", label: "Less" },
  { value: "bootstrap", label: "Bootstrap" },
  { value: "tailwind", label: "Tailwind CSS" },
  { value: "jquery", label: "jQuery" },
  { value: "webpack", label: "Webpack" },
  { value: "babel", label: "Babel" },
  { value: "gulp", label: "Gulp" },
  { value: "grunt", label: "Grunt" },
  { value: "git", label: "Git" },
  { value: "svn", label: "SVN" },
  { value: "docker", label: "Docker" },
  { value: "kubernetes", label: "Kubernetes" },
  { value: "jenkins", label: "Jenkins" },
  { value: "circleci", label: "CircleCI" },
  { value: "travis", label: "Travis CI" },
  { value: "aws", label: "AWS" },
  { value: "azure", label: "Azure" },
  { value: "gcp", label: "Google Cloud Platform" },
  { value: "heroku", label: "Heroku" },
  { value: "digitalocean", label: "DigitalOcean" },
  { value: "linux", label: "Linux" },
  { value: "unix", label: "Unix" },
  { value: "windows", label: "Windows" },
  { value: "macos", label: "macOS" },
  { value: "android", label: "Android" },
  { value: "ios", label: "iOS" },
  { value: "react_native", label: "React Native" },
  { value: "flutter", label: "Flutter" },
  { value: "xamarin", label: "Xamarin" },
  { value: "unity", label: "Unity" },
  { value: "unreal_engine", label: "Unreal Engine" },
  { value: "tensorflow", label: "TensorFlow" },
  { value: "pytorch", label: "PyTorch" },
  { value: "keras", label: "Keras" },
  { value: "scikit_learn", label: "scikit-learn" },
  { value: "pandas", label: "pandas" },
  { value: "numpy", label: "NumPy" },
  { value: "matplotlib", label: "Matplotlib" },
  { value: "opencv", label: "OpenCV" },
  { value: "hadoop", label: "Hadoop" },
  { value: "spark", label: "Apache Spark" },
  { value: "kafka", label: "Apache Kafka" },
  { value: "elasticsearch", label: "Elasticsearch" },
  { value: "logstash", label: "Logstash" },
  { value: "kibana", label: "Kibana" },
  { value: "grafana", label: "Grafana" },
  { value: "prometheus", label: "Prometheus" },
  { value: "tableau", label: "Tableau" },
  { value: "power_bi", label: "Power BI" },
  { value: "qlikview", label: "QlikView" },
  { value: "sas", label: "SAS" },
  { value: "spss", label: "SPSS" },
  { value: "photoshop", label: "Adobe Photoshop" },
  { value: "illustrator", label: "Adobe Illustrator" },
  { value: "indesign", label: "Adobe InDesign" },
  { value: "premiere_pro", label: "Adobe Premiere Pro" },
  { value: "after_effects", label: "Adobe After Effects" },
  { value: "figma", label: "Figma" },
  { value: "sketch", label: "Sketch" },
  { value: "invision", label: "InVision" },
  { value: "zeplin", label: "Zeplin" },
  { value: "jira", label: "Jira" },
  { value: "trello", label: "Trello" },
  { value: "asana", label: "Asana" },
  { value: "slack", label: "Slack" },
];

export const educationalOptions = [
  { value: "10th Standard", label: "10th Standard", step: 1 },
  { value: "12th Standard", label: "12th Standard", step: 2 },
  { value: "Bachelor's Degree", label: "Bachelor's Degree", step: 3 },
  { value: "Master's Degree", label: "Master's Degree", step: 4 },
  { value: "Doctorate", label: "Doctorate", step: 5 },
  { value: "Other", label: "Other", step: 1 },
];

export const genderOptions = [
  { value: "male", label: "Male" },
  { value: "female", label: "Female" },
  { value: "transgender", label: "Transgender" },
  { value: "non-binary", label: "Non-binary/Non-conforming" },
  { value: "prefer-not-to-say", label: "Prefer not to say" },
  { value: "other", label: "Other" },
];

export const phoneCountryCode = [
  { label: "+1", value: "+1" },
  { label: "+44", value: "+44" },
  { label: "+91", value: "+91" },
  { label: "+86", value: "+86" },
  { label: "+81", value: "+81" },
  { label: "+49", value: "+49" },
  { label: "+33", value: "+33" },
  { label: "+39", value: "+39" },
  { label: "+7", value: "+7" },
  { label: "+61", value: "+61" },
  { label: "+55", value: "+55" },
  { label: "+34", value: "+34" },
  { label: "+52", value: "+52" },
  { label: "+31", value: "+31" },
  { label: "+90", value: "+90" },
  { label: "+966", value: "+966" },
  { label: "+27", value: "+27" },
  { label: "+82", value: "+82" },
  { label: "+971", value: "+971" },
  { label: "+41", value: "+41" },
  { label: "+46", value: "+46" },
  { label: "+45", value: "+45" },
  { label: "+47", value: "+47" },
  { label: "+358", value: "+358" },
  { label: "+65", value: "+65" },
  { label: "+62", value: "+62" },
  { label: "+60", value: "+60" },
  { label: "+63", value: "+63" },
  { label: "+64", value: "+64" },
  { label: "+353", value: "+353" },
];

export const relationshipOptions = [
  { value: "parent", label: "Parent" },
  { value: "spouse", label: "Spouse" },
  { value: "relative", label: "Relative" },
  { value: "guardian", label: "Guardian" },
  { value: "friend", label: "Friend" },
  { value: "others", label: "Others" },
];

export const maritalStatusOptions = [
  { value: "single", label: "Single" },
  { value: "married", label: "Married" },
  { value: "divorced", label: "Divorced" },
  { value: "Widower/Widow", label: "Widower/Widow" },
  { value: "prefer not to say", label: "Prefer not to say" },
];

export const diplomaFieldsOfStudy = [
  { value: "engineering", label: "Engineering" },
  { value: "medicine", label: "Medicine" },
  { value: "arts", label: "Arts" },
  { value: "science", label: "Science" },
  { value: "commerce", label: "Commerce" },
];

export const bachelorFieldsOfStudy = [
  { value: "computer_science", label: "Computer Science" },
  { value: "engineering", label: "Engineering" },
  { value: "physics", label: "Physics" },
  { value: "chemistry", label: "Chemistry" },
  { value: "biology", label: "Biology" },
  { value: "mathematics", label: "Mathematics" },
  { value: "economics", label: "Economics" },
  { value: "business", label: "Business Administration" },
  { value: "literature", label: "Literature" },
  { value: "history", label: "History" },
  { value: "sociology", label: "Sociology" },
  { value: "psychology", label: "Psychology" },
  { value: "political_science", label: "Political Science" },
  { value: "philosophy", label: "Philosophy" },
  { value: "law", label: "Law" },
  { value: "medicine", label: "Medicine" },
  { value: "public_health", label: "Public Health" },
  { value: "education", label: "Education" },
  {
    value: "environmental_science",
    label: "Environmental Science",
  },
  { value: "neuroscience", label: "Neuroscience" },
  { value: "other", label: "Other" },
];

export const masterFieldsOfStudy = [
  { value: "computer_science", label: "Computer Science" },
  { value: "engineering", label: "Engineering" },
  { value: "physics", label: "Physics" },
  { value: "chemistry", label: "Chemistry" },
  { value: "biology", label: "Biology" },
  { value: "mathematics", label: "Mathematics" },
  { value: "economics", label: "Economics" },
  { value: "business", label: "Business Administration" },
  { value: "literature", label: "Literature" },
  { value: "history", label: "History" },
  { value: "sociology", label: "Sociology" },
  { value: "psychology", label: "Psychology" },
  { value: "political_science", label: "Political Science" },
  { value: "philosophy", label: "Philosophy" },
  { value: "law", label: "Law" },
  { value: "medicine", label: "Medicine" },
  { value: "public_health", label: "Public Health" },
  { value: "education", label: "Education" },
  {
    value: "environmental_science",
    label: "Environmental Science",
  },
  { value: "neuroscience", label: "Neuroscience" },
  { value: "other", label: "Other" },
];

export const doctorateFieldsOfStudy = [
  { value: "computer_science", label: "Computer Science" },
  { value: "engineering", label: "Engineering" },
  { value: "physics", label: "Physics" },
  { value: "chemistry", label: "Chemistry" },
  { value: "biology", label: "Biology" },
  { value: "mathematics", label: "Mathematics" },
  { value: "economics", label: "Economics" },
  { value: "business", label: "Business Administration" },
  { value: "literature", label: "Literature" },
  { value: "history", label: "History" },
  { value: "sociology", label: "Sociology" },
  { value: "psychology", label: "Psychology" },
  {
    value: "political_science",
    label: "Political Science",
  },
  { value: "philosophy", label: "Philosophy" },
  { value: "law", label: "Law" },
  { value: "medicine", label: "Medicine" },
  { value: "public_health", label: "Public Health" },
  { value: "education", label: "Education" },
  {
    value: "environmental_science",
    label: "Environmental Science",
  },
  { value: "neuroscience", label: "Neuroscience" },
  { value: "other", label: "Other" },
];

export const countryOptions = countryData.map((country) => ({
  value: country.country_name,
  label: country.country_name,
  country_id: country.country_id,
  shortname: country.sortname,
}));

export const stateOptions = stateData.map((state) => ({
  value: state.state_name,
  label: state.state_name,
  country_id: state.country_id,
  state_id: state.state_id,
}));

export const cityOptions = cityData.map((city) => ({
  value: city.city_name,
  label: city.city_name,
  state_id: city.state_id,
}));

export const institionOptions = institutionData.map((instituion) => ({
  value: instituion.name,
  label: instituion.name,
  country_shortname: instituion.country,
}));

export const BachelorDegreeOptions = [
  { value: "B.Tech", label: "B.Tech (Bachelor of Technology)" },
  { value: "B.E.", label: "B.E. (Bachelor of Engineering)" },
  { value: "B.Sc", label: "B.Sc (Bachelor of Science)" },
  { value: "B.A.", label: "B.A. (Bachelor of Arts)" },
  { value: "B.Com", label: "B.Com (Bachelor of Commerce)" },
  {
    value: "BBA",
    label: "BBA (Bachelor of Business Administration)",
  },
  {
    value: "BCA",
    label: "BCA (Bachelor of Computer Applications)",
  },
  {
    value: "B.Arch",
    label: "B.Arch (Bachelor of Architecture)",
  },
  { value: "B.Des", label: "B.Des (Bachelor of Design)" },
  { value: "BFA", label: "BFA (Bachelor of Fine Arts)" },
  { value: "LL.B", label: "LL.B (Bachelor of Laws)" },
  {
    value: "MBBS",
    label: "MBBS (Bachelor of Medicine, Bachelor of Surgery)",
  },
  { value: "B.Pharm", label: "B.Pharm (Bachelor of Pharmacy)" },
  {
    value: "B.Tech + M.Tech",
    label: "B.Tech + M.Tech (Integrated)",
  },
  { value: "BS + MS", label: "BS + MS (Integrated)" },
  { value: "BBA + MBA", label: "BBA + MBA (Integrated)" },
  {
    value: "B.Com + M.Com",
    label: "B.Com + M.Com (Integrated)",
  },
  { value: "BA + MA", label: "BA + MA (Integrated)" },
  { value: "B.Sc + M.Sc", label: "B.Sc + M.Sc (Integrated)" },
  {
    value: "B.Des + M.Des",
    label: "B.Des + M.Des (Integrated)",
  },
  {
    value: "B.Arch + M.Arch",
    label: "B.Arch + M.Arch (Integrated)",
  },
  {
    value: "B.Pharm + M.Pharm",
    label: "B.Pharm + M.Pharm (Integrated)",
  },
  { value: "Other", label: "Other" },
];

export const MasterDegreeOptions = [
  { value: "M.Tech", label: "M.Tech (Master of Technology)" },
  { value: "M.E.", label: "M.E. (Master of Engineering)" },
  { value: "M.Sc", label: "M.Sc (Master of Science)" },
  { value: "M.A.", label: "M.A. (Master of Arts)" },
  { value: "M.Com", label: "M.Com (Master of Commerce)" },
  {
    value: "MBA",
    label: "MBA (Master of Business Administration)",
  },
  {
    value: "MCA",
    label: "MCA (Master of Computer Applications)",
  },
  { value: "M.Arch", label: "M.Arch (Master of Architecture)" },
  { value: "M.Des", label: "M.Des (Master of Design)" },
  { value: "MFA", label: "MFA (Master of Fine Arts)" },
  { value: "LL.M", label: "LL.M (Master of Laws)" },
  { value: "M.Pharm", label: "M.Pharm (Master of Pharmacy)" },
  { value: "MPH", label: "MPH (Master of Public Health)" },
  { value: "MSW", label: "MSW (Master of Social Work)" },
  { value: "M.Ed", label: "M.Ed (Master of Education)" },
  {
    value: "MPA",
    label: "MPA (Master of Public Administration)",
  },
  { value: "Other", label: "Other" },
];
